package ifneeded Package 1.0 [list source [file join $dir Package.tcl]]
package ifneeded Http 2.1 [list source [file join $dir Http.tcl]]
package ifneeded Cookies 1.0 [list source [file join $dir Cookies.tcl]]

#package ifneeded Responder 1.0 [list source [file join $dir Responder.tcl]]

package ifneeded Debug 2.0 [list source [file join $dir Debug.tcl]]
package ifneeded Timer 1.0 [list source [file join $dir Timer.tcl]]
package ifneeded logging 1.0 [list source [file join $dir logging.tcl]]
package ifneeded Shell 1.0 [list source [file join $dir Shell.tcl]]
package ifneeded WubUtils 1.0 [list source [file join $dir WubUtils.tcl]]
package ifneeded Html 1.0 [list source [file join $dir Html.tcl]]
package ifneeded Url 1.0 [list source [file join $dir Url.tcl]]
package ifneeded record 1.0 [list source [file join $dir record.tcl]]
package ifneeded Form 2.0 [list source [file join $dir Form.tcl]]
package ifneeded profiler 1.0 [list source [file join $dir profiler.tcl]]
package ifneeded Query 2.0 [list source [file join $dir Query.tcl]]
package ifneeded Auth 1.0 [list source [file join $dir Auth.tcl]]
package ifneeded Dict 1.0 [list source [file join $dir Dict.tcl]]
package ifneeded View 3.0 [list source [file join $dir View.tcl]]
package ifneeded mktie 2.0 [list source [file join $dir mktie.tcl]]
package ifneeded UA 1.0 [list source [file join $dir UA.tcl]]
package ifneeded Report 1.0 [list source [file join $dir Report.tcl]]
package ifneeded Color 1.0 [list source [file join $dir Color.tcl]]

package ifneeded sgraph 1.0 [list source [file join $dir sgraph.tcl]]
package ifneeded mkdict_tie 1.0 [list source [file join $dir mkdict_tie.tcl]]
package ifneeded utf8 1.0 [list source [file join $dir utf8.tcl]]
package ifneeded passgen 1.0 [list source [file join $dir passgen.tcl]]
#package ifneeded captcha 1.0 [list source [file join $dir captcha.tcl]]
package ifneeded spiders 1.0 [list source [file join $dir spiders.tcl]]
package ifneeded Sitemap 1.0 [list source [file join $dir Sitemap.tcl]]
package ifneeded Sylk 1.0 [list source [file join $dir Sylk.tcl]]
package ifneeded Sscgi 1.0 [list source [file join $dir Sscgi.tcl]]

package ifneeded stx 1.1 [list source [file join $dir stx stx.tcl]]
package ifneeded stx2html 1.1 [list source [file join $dir stx stx2html.tcl]]

package ifneeded Mime 1.0 [list source [file join $dir Mime Mime.tcl]]
package ifneeded magiclib 1.0 [list source [file join $dir Mime magiclib.tcl]]
package ifneeded mime-magic 1.0 [list source [file join $dir Mime magic.mime.tcl]]

package ifneeded Coroonet 2.0 [list source [file join $dir Coroonet.tcl]]
package ifneeded SMTP 3.0 [list source [file join $dir SMTP.tcl]]
package ifneeded Mail 1.0 [list source [file join $dir Mail.tcl]]
package ifneeded Image 1.0 [list source [file join $dir Image.tcl]]
package ifneeded OO 1.0 [list source [file join $dir OO.tcl]]

package ifneeded tclhttpd 1.0 [list source [file join $dir tclhttpd.tcl]]
package ifneeded parsetcl 0.2 [list source [file join $dir parsetcl.tcl]]
package ifneeded Config 1.0 [list source [file join $dir Config.tcl]]
package ifneeded Store 1.0 [list source [file join $dir Store.tcl]]
package ifneeded Spelunker 1.0 [list source [file join $dir Spelunker.tcl]]
