# Steve Redler's WubTk demo

package require Tk
package require Query

proc buttonA args {
    set bText [.nb.tab1.b cget -text]
    set aText [.nb.tab1.a cget -text]
    .nb.tab1.a configure -text $bText
    .nb.tab1.b configure -text $aText
    .nb.tab1.g insert 2.4 "n1234567890\nsonia123"
}

proc buttonC args {
    global joe
    set joe "${joe}A"
    if {$joe != "bob" && [string first Mod [wm title .]] == -1} {
	wm title . "[wm title .] - Text Modified"
    }
    set joe [.nb.tab1.g get 2.4 3.8]
    .nb.tab1.g delete 2.4 3.8
}

proc buttonH {sobj dobj} {
    set text [$sobj get 0.0 end]
    set output ""
    foreach word [split $text] {
	for {set i 0} {$i<[string length $word]} {incr i} {
	    set char [string index $word $i]
	    append output "$char[string tolower $char$char]"
	}
	append output " "
    }
    $dobj configure -text $output
    wm title . "Done it!"
}

proc showCode {} {
    .nb.tab1.g delete 1.0 end
    set a 0
    .nb.tab1.g insert end [wm script]
    .nb.tab1.i configure -text "Cut n paste the above code into wish to compare!" -foreground orange -background black
}

proc readckrd {} {
    global joe k rb ckbt
    if {$ckbt} {
	.nb.tab1.m configure -background lightgreen
    } else {
	.nb.tab1.m configure -background pink
    }
}

proc getupload {} {
    puts stderr "getupload"
    set Q [Query parse [rq]]
    puts stderr "A"
    set X [Query nvmlist $Q]
    puts stderr "B"
    puts stderr $X
    .nb.tab1.g delete 1.0 end
    .nb.tab1.g insert end [lindex $X 1]
}

set ::fruit {apple orange peach pear cherry banana}
proc autocomplete {term} {
    set result {}
    foreach n $::fruit {
	if {[string match *$term* $n]} {
	    lappend result $n
	}
    }
    return $result
}

proc tkd {} {
    global joe bob ckbt rdbt scl

    # make a notebook
    notebook .nb -grid {0 0}
	
    frame .nb.tab1 -text Widgets -width 80%
    .nb add .nb.tab1

    button .nb.tab1.a -text "Press Me" -class moop -command buttonA -grid {0 0}
    button .nb.tab1.b -text "Don't Press Me" -command buttonA -grid {0 1}
    button .nb.tab1.f -text Google -command {wm redirect http://www.google.com} -grid {0 2}
    
    label .nb.tab1.e -text "Text:" -justify right -grid {1 0}
    entry .nb.tab1.d -textvariable joe -width 20 -grid {1 1}
    
    text .nb.tab1.g -width 60 -grid {3 0 1 3}
    .nb.tab1.g insert end "steve1234567890\ncolin1234567890\nsonia1234567890\nsybil1234567890"
    label .nb.tab1.i -text ""

    button .nb.tab1.h -text "Clear" -command {.nb.tab1.g delete 1.0 end; .nb.tab1.i configure -text ""} -grid {4 0}
    button .nb.tab1.j -text "Show Code" -command "showCode" -grid {4 2}

    button .nb.tab1.m -text Read -command readckrd -grid {5 2}

    frame .nb.tab1.sframe -text "Scale" -grid {6 0 1 3}
    entry .nb.tab1.sframe.q -textvariable ::slideV -width 4 -justify left -grid {0 1}
    scale .nb.tab1.sframe.p -text "slide me" -variable ::slideV -from 0 -to 100 -grid {0 0 -sticky nsew} -width 20em
    
    frame .nb.tab1.cframe -text "Checkbutton" -grid {7 0 1 3}
    checkbutton .nb.tab1.cframe.k -text "check me out" -variable ckbt -grid {0 0}
    entry .nb.tab1.cframe.o -textvariable ckbt -width 4 -justify right -grid {0 1}
    set k ""
    set rb ""

    frame .nb.tab1.coframe -text "Select" -grid {8 0 1 3}
    global combo
    set combo "steve"
    select .nb.tab1.coframe.combo -textvariable ::combo -values $::fruit -grid {0 0}
    entry .nb.tab1.coframe.combov -textvariable ::combo -grid {0 1} 

    frame .nb.tab1.acframe -text "AutoCompletion" -grid {9 0 1 3}
    entry .nb.tab1.acframe.text -textvariable ::combo -width 20 -complete $::fruit -grid {0 0}
    entry .nb.tab1.acframe.test -textvariable ::combo -grid {0 1}
    entry .nb.tab1.acframe.cmd -textvariable ::combo -width 20 -command autocomplete -grid {1 0}

    frame .nb.tab1.rframe -text "Radiobutton" -grid {10 0 1 3}
    radiobutton .nb.tab1.rframe.r1 -value apple -variable ::combo -text "Apple" -grid {0 0}
    radiobutton .nb.tab1.rframe.r2 -value banana -variable ::combo -text "Banana" -grid {1 0}
    radiobutton .nb.tab1.rframe.r3 -value cherry -variable ::combo -text "Cherry" -grid {2 0}

    set joe bob
    set ckbt 0
    set rdbt 0
    set scl 0
    
    frame .nb.tab2 -text Images -width 80%
    .nb add .nb.tab2
	
    image create photo .nb.tab2.image -url /icons/chart_accept.gif -grid {0 0}
    image create photo .image2 -url /icons/clock.gif
    button .nb.tab2.ibutton -image .image2 -command buttonC -text "image button" -valign middle -compound bottom -grid {0 1}
    
    frame .nb.tab2.frame -text "A Frame" -grid {0 2}
    image create photo .nb.tab2.frame.image3 -url /icons/application_edit.gif
    button .nb.tab2.frame.button -image .nb.tab2.frame.image3 -command buttonC -text "Push" -justify center -compound top -grid {0 0}

    frame .nb.tab3 -text Advanced -width 80%
    .nb add .nb.tab3

    frame .nb.tab3.frame -text "Date Entry" -grid {0 0}
    entry .nb.tab3.frame.d -textvariable date -width 20 -type date -grid {0 0}

    button .nb.tab3.error -text "Error Popup" -command {error "Told You So"} -grid {1 0}

    frame .nb.tab3.uframe -text "Upload File" -grid {2 0}
    upload .nb.tab3.uframe.f1 -title "Upload a file" -command getupload -grid {0 0}

    if {0} {
	frame .nb.tab3.tbframe -text "Toolbar" -grid {3 0}
	toolbar .nb.tab3.tbframe.tb -grid {3 0} -content {
	    [<buttons> {
	    [<icobutton> folder-open # Open Open]
	    [<icobutton> disk # Save Save]
		[<icobutton> trash # Delete Delete]
	    }]
	[<multibuttons> {
	    [<button> bold class "fg-button ui-state-default ui-corner-left" [<b> B]]
	    [<button> italic class "fg-button ui-state-default" [<i> I]]
	    [<button> underscore class "fg-button ui-state-default ui-corner-right" [<u> U]]
	}]
	    [<buttons> {
		[<icobutton> print # Print Print]
		[<icobutton> mail-closed # Email Email]
	    }]
	    [<buttons> {
		[<button> edit class "fg-button ui-state-default ui-state-active ui-priority-primary ui-corner-left" Edit]
		[<button> view class "fg-button ui-state-default ui-priority-primary ui-corner-right" View]
	    }]
	}
    }

    # make an accordion
    accordion .acc -grid {1 0}

    frame .acc.a1 -text "Accordion 0"
    .acc add .acc.a1
    label .acc.a1.txt -text "This is Accordion 0" -grid {0 0}

    frame .acc.a2 -text "Accordion 1"
    .acc add .acc.a2
    label .acc.a2.txt -text "This is Accordion 1" -grid {0 0}
	
    frame .acc.a3 -text "Accordion 2"
    .acc add .acc.a3
    label .acc.a3.txt -text "This is Accordion 2" -grid {0 0}

    toolbar .toolbar -grid 2
    set icnt 0
    foreach n {up back next down} {
	image create photo .toolbar.i$icnt -width 24 -url /icons/$n.gif
	button .toolbar.b$icnt -image .toolbar.i$icnt -command buttonC -grid $icnt
	incr icnt
    }
}

#auth valid tk /login/
tkd
